config/routes.rb
Rails.application.routes.draw do
	root to: 'posts#index'

	get 'users/index'

	resources :posts do
		resources :likes
	end

	resources :comments
	resources :profiles
	resources :requests

	devise_for :users
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :content, presence: true

  scope :friends_posts, -> (current_user) { where('user_id IN (?) OR user_id = ?', current_user.friend_ids, current_user.id).order("created_at DESC") }
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :user

	has_one_attached :avatar

	validate :correct_birth_date

	def correct_birth_date
    	errors.add(:birthday, "can't be in the future") if !birthday.blank? and birthday > Date.today
  	end
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :requester, class_name: 'User'
  	belongs_to :requestee, class_name: 'User'

  	def accept
    self.update_attributes(accepted: 1)
    Request.create!(requester_id: self.requestee_id, requestee_id: self.requester_id, accepted: 1)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :accepted_sent_requests, -> { where accepted: 1 }, foreign_key: :requester_id, class_name: 'Request'
  has_many :friends, through: :accepted_sent_requests, source: :requestee

  has_many :sent_requests, foreign_key: :requester_id, class_name: 'Request', dependent: :destroy
  has_many :received_requests, foreign_key: :requestee_id, class_name: 'Request', dependent: :destroy
  has_many :requestees, through: :sent_requests, dependent: :destroy
  has_many :requesters, through: :received_requests, dependent: :destroy

  after_create :make_profile

  def make_profile
  	self.create_profile.save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
		devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :comment_owner_check, only: [:edit, :update, :destroy]
	
	def create
		@comment = current_user.comments.build(comment_params)
	    if @comment.save
	      flash[:success] = 'Comment created'
	      redirect_to Post.find(@comment.post_id)
	    else
	      flash[:danger] = 'Something is wrong. Comment not created'
	      redirect_to root_url
	    end
	end

	def edit
		set_comment
	end

	def update
		if set_comment.update_attributes(comment_params)
			flash[:success] = "Comment updated!"
			redirect_to Post.find(comment.post_id)
		else
			render 'edit'
		end	
	end

	def destroy
		set_comment.destroy
		flash[:success] = "Comment was deleted."
		redirect_to root_path		
	end


	private
	def set_comment
		@comment = Comment.find(params[:id])		
	end

	def comment_params
		params.require(:comment).permit(:content, :post_id)		
	end

	def comment_owner_check
	    @user = set_comment.user
	    redirect_to(root_url) unless @user == current_user
  	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	before_action :set_post
	before_action :find_like, only: [:destroy]


	def create
		if already_liked?
    		flash[:notice] = "You can't like more than once"
  			else
    		@post.likes.create(user_id: current_user.id)
  		end
  		redirect_to root_path
	end

	def destroy
  		if !(already_liked?)
    		flash[:notice] = "Cannot unlike"
  		else
    		@like.destroy
  		end
  		redirect_to root_path
	end

	private

	def set_post
		@post = Post.find(params[:post_id])
	end

	def already_liked?
  		Like.where(user_id: current_user.id, post_id:
  		params[:post_id]).exists?
	end

	def find_like
   		@like = @post.likes.find(params[:id])
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :post_owner_check, only: [:edit, :update, :destroy]

	def index
		@post = Post.new
		@posts = Post.friends_posts(current_user)
		@comment = Comment.new		
	end

	def show
		set_post
		@comment = Comment.new
	end

	def create
    @post = current_user.posts.build(post_params)
	    if @post.save
	      flash[:post_success] = 'Post successful!'
	      redirect_to root_url
	    else
	      flash[:post_failure] = 'Post did not save - text content required.'
	      redirect_to root_url
	    end
	end

	def edit
		set_post		
	end

	def update
		if set_post.update_attributes(post_params)
			flash[:success] = "Post updated!"
			redirect_to post_path
		else
			render 'edit'
		end		
	end

	def destroy
		set_post.destroy
		flash[:success] = "Post was deleted."
		redirect_to root_path
	end

	private
	def set_post
		@post = Post.find(params[:id])		
	end

	def post_params
		params.require(:post).permit(:content)		
	end

	def post_owner_check
	    @user = set_post.user
	    redirect_to(root_url) unless @user == current_user
  	end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController


	def show
		@profile = Profile.find(params[:id])
		@posts = @profile.user.posts.order("created_at DESC")
		@comment = Comment.new		
	end

	def edit
		@profile = current_user.profile
	end

	def update
		if set_profile.update_attributes(profile_params)
    		flash[:success] = "Your profile has been updated"
      		redirect_to set_profile
    	else
      		render 'edit'
    	end
	end

	private
	def set_profile
		@profile = Profile.find(params[:id])
	end

	def profile_params
		params.require(:profile).permit(:about_me, :location, :birthday, :avatar)
	end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController

	def index
		@users = current_user.requesters.where('requests.accepted = ?', 0)
	end

	def update
		@request = Request.find(params[:id])
	    @request.accept
	    flash[:success] = 'Friend Request Accepted!'
	    redirect_to User.find(params[:request][:requester_id]).profile
	end

	def create
		@request = current_user.sent_requests.build(request_params)
	    if @request.save
	      flash[:success] = 'Friend request sent!'
	      redirect_to root_url
	    else
	      render root_url
	    end
	end

	private
	def request_params
		params.require(:request).permit(:requestee_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.where('id != ?' , current_user.id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <div class="form-group">
    <%= f.label 'Leave comment' %><br>
    <%= f.text_area :content, class: 'form-control', autofocus: true, placeholder: 'Any commnets?' %>
    <%= f.hidden_field :post_id, value: @post.id %>
  </div>
  <%= f.submit :comment, class: 'btn btn-primary'%>
<% end %>

app/views/posts/_form.html.erb
<div class="form-container">
	<%= form_for(@post) do |f| %>
	  <div class="form-group">
	    <%= f.label 'Update status' %><br>
	      <%= f.text_area :content, class: 'form-control', autofocus: true, placeholder: 'What\'s up?' %>
	  </div>
	  <%= f.submit :post, class: 'btn btn-primary'%>
	<% end %>
</div>

app/views/posts/_post.html.erb
<% @posts.each do |post| %>
	<div class="post-container">
		<div class="">			
			<p>
				<%=link_to(post.user.profile) do %>
					<%= post.user.first_name %>
					<%= post.user.last_name %>
				<% end %>
				<p>
					<%= post.content %>					
				</p>
			</p>
				<%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%>
				<% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
				<% if pre_like %>
					<%= button_to 'Unlike', post_like_path(post, pre_like), method: :delete %>
				<% else %>
					<%= button_to 'Like', post_likes_path(post), method: :post %>
				<% end %>

			<%= link_to 'Show', post_path(post) %>
			<% if current_user.id == post.user_id %>
				<%= link_to 'Edit', edit_post_path(post) %>
				<%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
			<% end %>
		</div>
		<div class="container">
			<% post.comments.each do |comment| %>
				<div class="container">
					
					<%=link_to(comment.user.profile) do %>
						<%= post.user.first_name %>
						<%= post.user.last_name %>
					<% end %>
					<p><%= comment.content %></p>
				</div>
			<% end %>
	
			<%= form_for(@comment) do |f| %>
				<div class="form-group">
					<%= f.label 'Leave comment' %><br>
					<%= f.text_area :content, class: 'form-control', autofocus: true, placeholder: 'Any commnets?' %>
					<%= f.hidden_field :post_id, value: post.id %>
				</div>
				<%= f.submit :comment, class: 'btn btn-primary'%>
			<% end %>
		</div>
	</div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
	<p><%= render 'form' %></p>
</div>

app/views/posts/index.html.erb
<h1 align="center">Posts feed</h1>

<div class="container">
	<p><%= render 'form' %></p>	
	<p><%= render 'post' %></p>
</div>

app/views/posts/new.html.erb
<div class="container">
	<p><%= render 'form' %></p>
</div>

app/views/posts/show.html.erb
<div class="container">
	
	<%= @post.user.first_name %>
	<%= @post.user.last_name %>

	<div>
		<h1><%= @post.content %></h1>
	</div>

	

	<%= @post.likes.count %> <%= (@post.likes.count) == 1 ? 'Like' : 'Likes'%>

	<% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
	<% if pre_like %>
  		<%= button_to 'Unlike', post_like_path(@post, pre_like), method: :delete %>
	<% else %>
  		<%= button_to 'Like', post_likes_path(@post), method: :post %>
	<% end %>

	<div class="container">
		<p><%= render 'comments/form' %></p>

		<% @post.comments.each do |comment| %>
			<% user = User.find(comment.user_id) %>
			<div class="container">
				Comment by: <%= link_to "#{user.first_name} #{user.last_name}", user.profile %>
				<p><%= comment.content %></p>
			</div>
		<% end %>
	</div>
	
</div>

app/views/profiles/edit.html.erb
<div class="container">
    <strong><h2><%= current_user.email %></h2></strong>

    <%= form_for @profile do |f| %>

    <div>
        <%= f.label :birthday, "Birthday" %>
        <br/>
        <%= f.date_field :birthday, autocomplete: "off" %>
        <br/>

        <%= f.label :location, "City" %>
        <br/>
        <%= f.text_field :location %>
        <br/>

        <%= f.label :about_me, "About Me" %>
        <br/>
        <%= f.text_area :about_me %>
        <br/>

        <%= f.label :avatar, "Avatar" %>
        <br/>
        <%= f.file_field :avatar %>
        <br/>

    </div>

    <%= f.submit "Save Your Profile" %>
    <br/>

    <% end %>
</div>

app/views/profiles/show.html.erb
<div class="container">
	<% if @profile.user == current_user %>
	    <%= link_to "Edit profile", edit_profile_path(current_user.profile)%>
	<% end %>

	<% unless current_user == @profile.user %>
	    <% if current_user.requesters.where('requests.accepted = ?', 0).include?(@profile.user) %>
	      <%= link_to "Accept Friend Request", request_path(id: current_user.received_requests.find_by(requester_id: @profile.user.id).id, request: { requester_id: @profile.user.id }), method: :put %>
	    <% elsif current_user.requesters.include?(@profile.user) %>
	    <% elsif !current_user.requestees.include?(@profile.user) %>
	      <%= link_to "Add friend", requests_path(request: { requestee_id: @profile.user.id }), method: :post %>
	    <% end %>
	  <% end %>


	<div class="row">
		<div class="col-md-3">
			<p>
				<% if@profile.avatar.attached? %>
					<image src="<%=(url_for(@profile.avatar))%>" height="100">
				<% end %>
				<br/>
				<strong>Date of Birth:</strong>
				<%= @profile.birthday %>
				<br/>
				<strong>City:</strong>
				<%= @profile.location %>
				<br/>
				<strong>About Me:</strong>
				<%= @profile.about_me %>
			</p>
		</div>
		<div class="col-md-8">		
			<p><%= render 'posts/post' %></p>
		</div>  
	</div>

</div>

app/views/requests/index.html.erb
<div class="container">
  <h1>Friend Requests</h1>
  <% @users.each do |user| %>
    <div>
      <%= link_to(user.profile) do %>
        <%= user.first_name %>
        <%= user.last_name %>
      <% end %>
      <% if current_user.requesters.where('requests.accepted = ?', 0).include?(user) %>
        <%= button_to "Confirm", request_path(id: current_user.received_requests.find_by(requester_id: user.id).id, request: { requester_id: user.id }), method: :put %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
	<% @users.each do |user| %>
		<strong><%= link_to(user.profile) do %>
			<%= user.first_name %>
			<%= user.last_name %>
		<% end %></strong>
		
		<% if current_user.requesters.where('requests.accepted = ?', 0).include?(user) %>
			<%= button_to "Confirm", request_path(id: current_user.received_requests.find_by(requester_id: user.id).id, request: { requester_id: user.id }), method: :put, class: "add-friend-button users-index-button accept-color" %>
		<% elsif current_user.requesters.include?(user) %>
		<% elsif !current_user.requestees.include?(user) %>
			<%= button_to "Add Friend", requests_path(request: { requestee_id: user.id }), method: :post, class: "add-friend-button users-index-button" %>
		<% end %>
		<p></p>
	<% end %>
</div>